/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estefanyh
 */
import java.text.DecimalFormat;
public class mennu extends javax.swing.JFrame {

    /**
     * Creates new form mennu
     */
    public mennu() {
        initComponents();
         simple_panel.setVisible(true);
        multiple_panel.setVisible(false);
        bino_panel.setVisible(false);
        pa1.setEditable(false);
        pas1.setEditable(false);
        pa2.setEditable(false);
        pb2.setEditable(false);
        avb2.setEditable(false);
        aib2.setEditable(false);
        pac2.setEditable(false);
        pbc2.setEditable(false);
        paub2.setEditable(false);
        db3.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        simple = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        binomial = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        multiple = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        simple_panel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nr1 = new javax.swing.JTextField();
        ne1 = new javax.swing.JTextField();
        borrar1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pas1 = new javax.swing.JTextField();
        pa1 = new javax.swing.JTextField();
        calcular1 = new javax.swing.JButton();
        multiple_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        na2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nr2 = new javax.swing.JTextField();
        nb2 = new javax.swing.JTextField();
        calcular2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pb2 = new javax.swing.JTextField();
        pa2 = new javax.swing.JTextField();
        avb2 = new javax.swing.JTextField();
        aib2 = new javax.swing.JTextField();
        pac2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pbc2 = new javax.swing.JTextField();
        paub2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        bino_panel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ne3 = new javax.swing.JTextField();
        nex3 = new javax.swing.JTextField();
        pe3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        db3 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(88, 184, 182));

        simple.setBackground(new java.awt.Color(170, 220, 215));
        simple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpleMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(252, 255, 247));
        jLabel1.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel1.setText("Simple");

        javax.swing.GroupLayout simpleLayout = new javax.swing.GroupLayout(simple);
        simple.setLayout(simpleLayout);
        simpleLayout.setHorizontalGroup(
            simpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        simpleLayout.setVerticalGroup(
            simpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        binomial.setBackground(new java.awt.Color(170, 220, 215));
        binomial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                binomialMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(252, 255, 247));
        jLabel2.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Binomial");

        javax.swing.GroupLayout binomialLayout = new javax.swing.GroupLayout(binomial);
        binomial.setLayout(binomialLayout);
        binomialLayout.setHorizontalGroup(
            binomialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, binomialLayout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44))
        );
        binomialLayout.setVerticalGroup(
            binomialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, binomialLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        multiple.setBackground(new java.awt.Color(170, 220, 215));
        multiple.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multipleMouseClicked(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(252, 255, 247));
        jLabel3.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel3.setText("Multiple");

        javax.swing.GroupLayout multipleLayout = new javax.swing.GroupLayout(multiple);
        multiple.setLayout(multipleLayout);
        multipleLayout.setHorizontalGroup(
            multipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        multipleLayout.setVerticalGroup(
            multipleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multipleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(binomial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(multiple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(simple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(simple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(multiple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(binomial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        simple_panel.setBackground(new java.awt.Color(252, 255, 247));

        jLabel4.setBackground(new java.awt.Color(252, 255, 247));
        jLabel4.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel4.setText("Número de resultados posibles");

        jLabel5.setBackground(new java.awt.Color(252, 255, 247));
        jLabel5.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel5.setText("Número de eventos ");

        borrar1.setText("Borrar");
        borrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrar1MouseClicked(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(252, 255, 247));
        jLabel6.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel6.setText("P(A)=");

        jLabel7.setBackground(new java.awt.Color(252, 255, 247));
        jLabel7.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel7.setText("P(A')=");

        calcular1.setText("Calcular");
        calcular1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcular1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout simple_panelLayout = new javax.swing.GroupLayout(simple_panel);
        simple_panel.setLayout(simple_panelLayout);
        simple_panelLayout.setHorizontalGroup(
            simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simple_panelLayout.createSequentialGroup()
                        .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(simple_panelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(pa1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(simple_panelLayout.createSequentialGroup()
                                    .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5))
                                    .addGap(18, 18, 18)
                                    .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ne1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nr1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(simple_panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(pas1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simple_panelLayout.createSequentialGroup()
                    .addContainerGap(276, Short.MAX_VALUE)
                    .addComponent(calcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );
        simple_panelLayout.setVerticalGroup(
            simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ne1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(pa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(borrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(simple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(simple_panelLayout.createSequentialGroup()
                    .addGap(104, 104, 104)
                    .addComponent(calcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(151, Short.MAX_VALUE)))
        );

        multiple_panel.setBackground(new java.awt.Color(252, 255, 247));

        jLabel8.setBackground(new java.awt.Color(252, 255, 247));
        jLabel8.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel8.setText("Número de resultados posibles");

        jLabel9.setBackground(new java.awt.Color(252, 255, 247));
        jLabel9.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel9.setText("Número de eventos en B");

        jLabel10.setBackground(new java.awt.Color(252, 255, 247));
        jLabel10.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel10.setText("Número de eventos en A");

        calcular2.setText("Calcular");
        calcular2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcular2MouseClicked(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(252, 255, 247));
        jLabel11.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel11.setText("P(A)");

        jLabel12.setBackground(new java.awt.Color(252, 255, 247));
        jLabel12.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel12.setText("P(B)");

        jLabel13.setBackground(new java.awt.Color(252, 255, 247));
        jLabel13.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel13.setText("P(A∩B)");

        jLabel14.setBackground(new java.awt.Color(252, 255, 247));
        jLabel14.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel14.setText("P(A|B)");

        jLabel15.setBackground(new java.awt.Color(252, 255, 247));
        jLabel15.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel15.setText("P(A')");

        jLabel16.setBackground(new java.awt.Color(252, 255, 247));
        jLabel16.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel16.setText("P(B')");

        jLabel17.setBackground(new java.awt.Color(252, 255, 247));
        jLabel17.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel17.setText("P(B∪A)");

        jButton4.setText("Borrar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout multiple_panelLayout = new javax.swing.GroupLayout(multiple_panel);
        multiple_panel.setLayout(multiple_panelLayout);
        multiple_panelLayout.setHorizontalGroup(
            multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multiple_panelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiple_panelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calcular2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nb2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(multiple_panelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nr2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiple_panelLayout.createSequentialGroup()
                        .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(multiple_panelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pa2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(multiple_panelLayout.createSequentialGroup()
                                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(multiple_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(multiple_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(avb2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(multiple_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(aib2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(multiple_panelLayout.createSequentialGroup()
                                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(multiple_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pbc2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(multiple_panelLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pac2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, multiple_panelLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paub2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        multiple_panelLayout.setVerticalGroup(
            multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(multiple_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(na2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(calcular2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pac2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(pbc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(avb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(paub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(multiple_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(aib2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bino_panel.setBackground(new java.awt.Color(252, 255, 247));

        jLabel18.setBackground(new java.awt.Color(252, 255, 247));
        jLabel18.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel18.setText("Número de eventos");

        jLabel19.setBackground(new java.awt.Color(252, 255, 247));
        jLabel19.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel19.setText("Número de éxito");

        jLabel20.setBackground(new java.awt.Color(252, 255, 247));
        jLabel20.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel20.setText("Probabilidad de éxito");

        jButton5.setText("Calcular");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(252, 255, 247));
        jLabel21.setFont(new java.awt.Font("Zapf Dingbats", 0, 18)); // NOI18N
        jLabel21.setText("Distribución binamial");

        jButton6.setText("Borrar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout bino_panelLayout = new javax.swing.GroupLayout(bino_panel);
        bino_panel.setLayout(bino_panelLayout);
        bino_panelLayout.setHorizontalGroup(
            bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bino_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(bino_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bino_panelLayout.createSequentialGroup()
                        .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(24, 24, 24)
                        .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pe3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nex3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ne3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bino_panelLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(db3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        bino_panelLayout.setVerticalGroup(
            bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bino_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ne3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(nex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(pe3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(bino_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(db3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 167, Short.MAX_VALUE)
                    .addComponent(bino_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 166, Short.MAX_VALUE)
                    .addComponent(multiple_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(simple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bino_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(multiple_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpleMouseClicked
        // TODO add your handling code here:
        simple_panel.setVisible(true);
        multiple_panel.setVisible(false);
        bino_panel.setVisible(false);
    }//GEN-LAST:event_simpleMouseClicked

    private void multipleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multipleMouseClicked
        // TODO add your handling code here:
        simple_panel.setVisible(false);
        multiple_panel.setVisible(true);
        bino_panel.setVisible(false);
    }//GEN-LAST:event_multipleMouseClicked

    private void binomialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_binomialMouseClicked
        // TODO add your handling code here:
        
        simple_panel.setVisible(false);
        multiple_panel.setVisible(false);
        bino_panel.setVisible(true);
    }//GEN-LAST:event_binomialMouseClicked

    private void calcular1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcular1MouseClicked
        // TODO add your handling code here:
        double p1,ps1,da1,da2;
        DecimalFormat decimales = new DecimalFormat("0.0000");
        String r1,r2;
        da1=Double.parseDouble(nr1.getText());
        da2=Double.parseDouble(ne1.getText());
        p1=da2/da1;
        ps1=1-p1;
        r1=String.valueOf(decimales.format(p1));
        r2=String.valueOf(decimales.format(ps1));
        pa1.setText(r1);
        pas1.setText(r2);
        
    }//GEN-LAST:event_calcular1MouseClicked

    private void borrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrar1MouseClicked
        // TODO add your handling code here:
        pa1.setText(null);
        pas1.setText(null);
        nr1.setText(null);
        ne1.setText(null);
        
    }//GEN-LAST:event_borrar1MouseClicked

    private void calcular2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcular2MouseClicked
        // TODO add your handling code here:
        double da3,da4,da5,a2,b2,ainb,aib,ac,bc,aub;
        DecimalFormat decimales = new DecimalFormat("0.0000");
        String r3,r4,r5,r6,r7,r8,r9;
        da3=Double.parseDouble(nr2.getText());
        da4=Double.parseDouble(na2.getText());
        da5=Double.parseDouble(nb2.getText());
        a2=da4/da3;
        b2=da5/da3;
        ainb=a2*b2;
        aib=ainb/b2;
        ac=1-a2;
        bc=1-b2;
        aub=(a2+b2)-ainb;
         r3=String.valueOf(decimales.format(a2));
         r4=String.valueOf(decimales.format(b2));
         r5=String.valueOf(decimales.format(ainb));
         r6=String.valueOf(decimales.format(aib));
         r7=String.valueOf(decimales.format(ac));
         r8=String.valueOf(decimales.format(bc));
         r9=String.valueOf(decimales.format(aub));
         
            pa2.setText(r3);
            pb2.setText(r4);
            avb2.setText(r5);
            aib2.setText(r6);
            pac2.setText(r7);
            pbc2.setText(r8);
            paub2.setText(r9);                
    }//GEN-LAST:event_calcular2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        pa2.setText(null);
            pb2.setText(null);
            avb2.setText(null);
            aib2.setText(null);
            pac2.setText(null);
            pbc2.setText(null);
            paub2.setText(null);
            nr2.setText(null);
            na2.setText(null);
            nb2.setText(null);
            
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        double da6,da7,da8,comb, result,de,di;   
        String r10,r11;
         DecimalFormat decimales = new DecimalFormat("0.0000");
        da6=Double.parseDouble(ne3.getText());//4
        da7=Double.parseDouble(nex3.getText());//2
        da8=Double.parseDouble(pe3.getText());//0.8
        comb=fact(da6)/(fact(da7)*fact(da6-da7));
        de=1-da8;
        di=da6-da7;
        result=comb*((Math.pow(da8,da7))*(Math.pow(de,di)));
        r10=String.valueOf(decimales.format(result));
        db3.setText(r10);

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        db3.setText(null);
        ne3.setText(null);
        nex3.setText(null);
        pe3.setText(null);
    }//GEN-LAST:event_jButton6MouseClicked
double fact (double x){
    int prod=1;
    int i=1;
    while (i<=x){
        prod=prod*i;
        i=i+1;       
    }
    return prod;
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mennu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mennu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mennu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mennu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mennu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aib2;
    private javax.swing.JTextField avb2;
    private javax.swing.JPanel bino_panel;
    private javax.swing.JPanel binomial;
    private javax.swing.JButton borrar1;
    private javax.swing.JButton calcular1;
    private javax.swing.JButton calcular2;
    private javax.swing.JTextField db3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel multiple;
    private javax.swing.JPanel multiple_panel;
    private javax.swing.JTextField na2;
    private javax.swing.JTextField nb2;
    private javax.swing.JTextField ne1;
    private javax.swing.JTextField ne3;
    private javax.swing.JTextField nex3;
    private javax.swing.JTextField nr1;
    private javax.swing.JTextField nr2;
    private javax.swing.JTextField pa1;
    private javax.swing.JTextField pa2;
    private javax.swing.JTextField pac2;
    private javax.swing.JTextField pas1;
    private javax.swing.JTextField paub2;
    private javax.swing.JTextField pb2;
    private javax.swing.JTextField pbc2;
    private javax.swing.JTextField pe3;
    private javax.swing.JPanel simple;
    private javax.swing.JPanel simple_panel;
    // End of variables declaration//GEN-END:variables
}
